create extension if not exists pgcrypto;
create table if not exists public.trades(id uuid primary key default gen_random_uuid(),user_id uuid not null references auth.users(id) on delete cascade,trade_date date not null,exchange text not null,pair text not null,side text not null,position_status text not null default 'Closed' check (position_status in ('Planned','Open','Closed')),entry numeric not null,stop_loss numeric not null,take_profit numeric,position_size numeric,leverage numeric default 1,contract_size numeric,risk_usd numeric not null,pnl_usd numeric not null,r_multiple numeric not null,setup text,plan_followed boolean default true,mistake text default 'None',notes text,violation boolean default false,opened_at timestamptz,closed_at timestamptz,close_reason text,created_at timestamptz default now());
create table if not exists public.risk_settings(user_id uuid primary key references auth.users(id) on delete cascade,equity numeric default 14000,max_risk_pct numeric default 1,daily_loss_limit numeric default 315,max_trades_day integer default 5,max_loss_streak integer default 3,updated_at timestamptz default now());
alter table public.trades enable row level security; alter table public.risk_settings enable row level security;
create policy "own trades select" on public.trades for select using(auth.uid()=user_id);
create policy "own trades insert" on public.trades for insert with check(auth.uid()=user_id);
create policy "own trades update" on public.trades for update using(auth.uid()=user_id) with check(auth.uid()=user_id);
create policy "own trades delete" on public.trades for delete using(auth.uid()=user_id);
create policy "own risk select" on public.risk_settings for select using(auth.uid()=user_id);
create policy "own risk insert" on public.risk_settings for insert with check(auth.uid()=user_id);
create policy "own risk update" on public.risk_settings for update using(auth.uid()=user_id) with check(auth.uid()=user_id);
create table if not exists public.dca_positions(id uuid primary key default gen_random_uuid(),user_id uuid not null references auth.users(id) on delete cascade,exchange text not null,pair text not null,current_price numeric,notes text,created_at timestamptz default now());
create table if not exists public.dca_entries(id uuid primary key default gen_random_uuid(),user_id uuid not null references auth.users(id) on delete cascade,position_id uuid not null references public.dca_positions(id) on delete cascade,entry_date timestamptz not null,entry_price numeric not null check(entry_price>0),amount numeric not null check(amount>0),amount_type text not null check(amount_type in ('Quantity','USDT','Lots')),contract_size numeric,fee_usdt numeric not null default 0 check(fee_usdt>=0),notes text,created_at timestamptz default now());
alter table public.dca_positions enable row level security; alter table public.dca_entries enable row level security;
create policy "own dca positions select" on public.dca_positions for select to authenticated using((select auth.uid())=user_id);
create policy "own dca positions insert" on public.dca_positions for insert to authenticated with check((select auth.uid())=user_id);
create policy "own dca positions update" on public.dca_positions for update to authenticated using((select auth.uid())=user_id) with check((select auth.uid())=user_id);
create policy "own dca positions delete" on public.dca_positions for delete to authenticated using((select auth.uid())=user_id);
create policy "own dca entries select" on public.dca_entries for select to authenticated using((select auth.uid())=user_id);
create policy "own dca entries insert" on public.dca_entries for insert to authenticated with check((select auth.uid())=user_id and exists(select 1 from public.dca_positions p where p.id=position_id and p.user_id=(select auth.uid())));
create policy "own dca entries update" on public.dca_entries for update to authenticated using((select auth.uid())=user_id) with check((select auth.uid())=user_id and exists(select 1 from public.dca_positions p where p.id=position_id and p.user_id=(select auth.uid())));
create policy "own dca entries delete" on public.dca_entries for delete to authenticated using((select auth.uid())=user_id);
grant select,insert,update,delete on table public.dca_positions,public.dca_entries to authenticated;
