"use client";
import {useEffect,useMemo,useState} from "react"; import {supabase} from "../../lib/supabase";
const cash=n=>"$"+Number(n||0).toLocaleString(undefined,{minimumFractionDigits:2,maximumFractionDigits:2});
const today=()=>{let d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`};
export default function Dashboard(){
 const s=useMemo(()=>supabase(),[]),[user,setUser]=useState(null),[trades,setTrades]=useState([]),[tab,setTab]=useState("Dashboard"),[month,setMonth]=useState(new Date()),[risk,setRisk]=useState({equity:14000,max_risk_pct:1,daily_loss_limit:315,max_trades_day:5,max_loss_streak:3});
 const [f,setF]=useState({trade_date:today(),exchange:"Binance",pair:"BTCUSDT",side:"Long",entry:"",stop_loss:"",take_profit:"",risk_usd:"",pnl_usd:"",setup:"",plan_followed:"yes",mistake:"None",notes:""});
 async function load(){let {data:{user:u}}=await s.auth.getUser();if(!u){location.href="/login";return}setUser(u);let {data:t}=await s.from("trades").select("*").order("trade_date",{ascending:false});setTrades(t||[]);let {data:r}=await s.from("risk_settings").select("*").eq("user_id",u.id).maybeSingle();if(r)setRisk(r)}
 useEffect(()=>{load()},[]);
 async function add(e){e.preventDefault();let r=+f.risk_usd,p=+f.pnl_usd;if(!(r>0))return alert("Risk must be > 0");let violation=f.plan_followed==="no"||f.mistake!=="None"||r>(+risk.equity*+risk.max_risk_pct/100);let {error}=await s.from("trades").insert({user_id:user.id,...f,plan_followed:f.plan_followed==="yes",entry:+f.entry,stop_loss:+f.stop_loss,take_profit:f.take_profit?+f.take_profit:null,risk_usd:r,pnl_usd:p,r_multiple:p/r,violation});if(error)return alert(error.message);setF({...f,entry:"",stop_loss:"",take_profit:"",risk_usd:"",pnl_usd:"",setup:"",notes:"",mistake:"None",plan_followed:"yes"});load();setTab("Dashboard")}
 async function saveRisk(){let {error}=await s.from("risk_settings").upsert({user_id:user.id,equity:+risk.equity,max_risk_pct:+risk.max_risk_pct,daily_loss_limit:+risk.daily_loss_limit,max_trades_day:+risk.max_trades_day,max_loss_streak:+risk.max_loss_streak},{onConflict:"user_id"});alert(error?error.message:"Risk settings saved")}
 async function del(id){if(confirm("Delete trade?")){await s.from("trades").delete().eq("id",id);load()}}
 let mk=`${month.getFullYear()}-${String(month.getMonth()+1).padStart(2,"0")}`,mt=trades.filter(x=>x.trade_date.startsWith(mk)),net=mt.reduce((a,x)=>a+ +x.pnl_usd,0),wins=mt.filter(x=>+x.pnl_usd>0),loss=mt.filter(x=>+x.pnl_usd<0),gp=wins.reduce((a,x)=>a+ +x.pnl_usd,0),gl=Math.abs(loss.reduce((a,x)=>a+ +x.pnl_usd,0)),pf=gl?gp/gl:gp?"∞":"0.00",wr=mt.length?wins.length/mt.length*100:0,avgR=mt.length?mt.reduce((a,x)=>a+ +x.r_multiple,0)/mt.length:0,viol=mt.filter(x=>x.violation).length,comp=mt.length?(mt.length-viol)/mt.length*100:100;
 let daily={};mt.forEach(x=>{daily[x.trade_date]??={pnl:0,n:0,v:0};daily[x.trade_date].pnl+=+x.pnl_usd;daily[x.trade_date].n++;if(x.violation)daily[x.trade_date].v++});
 let td=trades.filter(x=>x.trade_date===today()),tp=td.reduce((a,x)=>a+ +x.pnl_usd,0),stop=tp<=-Math.abs(+risk.daily_loss_limit)||td.length>=+risk.max_trades_day;
 function cal(){let y=month.getFullYear(),m=month.getMonth(),first=new Date(y,m,1).getDay(),days=new Date(y,m+1,0).getDate();return <div className="cal">{[...Array(first)].map((_,i)=><div className="day blank" key={"b"+i}/>)}{[...Array(days)].map((_,i)=>{let d=i+1,k=`${y}-${String(m+1).padStart(2,"0")}-${String(d).padStart(2,"0")}`,x=daily[k];return <div className={"day "+(x?(x.pnl>0?"green":x.pnl<0?"red":""):"")} key={k}><span>{d}</span>{x&&<><b className={x.pnl>=0?"pos":"neg"}>{cash(x.pnl)}</b><small>{x.n} trades{x.v?" · ⚠":""}</small></>}</div>})}</div>}
 return <main className="shell"><header><div><small>PRIVATE TRADING OS</small><h1>NØS Trading Monitor</h1></div><div><b className={stop?"status stop":"status ready"}>{stop?"STOP TRADING":"READY"}</b><button className="ghost" onClick={async()=>{await s.auth.signOut();location.href="/login"}}>Logout</button></div></header>
 <nav>{["Dashboard","Calendar","Journal","Risk"].map(x=><button className={tab===x?"active":""} onClick={()=>setTab(x)} key={x}>{x}</button>)}</nav>
 {tab==="Dashboard"&&<><div className="kpis">{[["Net P&L",cash(net),net>=0?"pos":"neg"],["Win Rate",wr.toFixed(1)+"%",""],["Profit Factor",typeof pf==="number"?pf.toFixed(2):pf,""],["Average R",avgR.toFixed(2)+"R",""],["Compliance",comp.toFixed(1)+"%",""],["Today",cash(tp),tp>=0?"pos":"neg"]].map(x=><div className="card" key={x[0]}><span>{x[0]}</span><b className={x[2]}>{x[1]}</b></div>)}</div><Panel title="Monthly P&L Calendar" month={month} setMonth={setMonth}>{cal()}</Panel></>}
 {tab==="Calendar"&&<Panel title="Daily Calendar" month={month} setMonth={setMonth}>{cal()}</Panel>}
 {tab==="Journal"&&<><Panel title="Add Trade"><form className="form" onSubmit={add}>{Object.entries({trade_date:"date",exchange:"select",pair:"text",side:"select",entry:"number",stop_loss:"number",take_profit:"number",risk_usd:"number",pnl_usd:"number",setup:"text",plan_followed:"plan",mistake:"mistake"}).map(([k,type])=><label key={k}><span>{k.replaceAll("_"," ")}</span>{type==="select"?<select value={f[k]} onChange={e=>setF({...f,[k]:e.target.value})}>{k==="exchange"?["Binance","OKX","Bitkub","XM"].map(o=><option key={o}>{o}</option>):["Long","Short"].map(o=><option key={o}>{o}</option>)}</select>:type==="plan"?<select value={f[k]} onChange={e=>setF({...f,[k]:e.target.value})}><option value="yes">Yes</option><option value="no">No</option></select>:type==="mistake"?<select value={f[k]} onChange={e=>setF({...f,[k]:e.target.value})}>{["None","FOMO","Revenge Trade","Over Risk","No Setup","Moved Stop","Early Exit","Overtrade"].map(o=><option key={o}>{o}</option>)}</select>:<input type={type} step="any" value={f[k]} onChange={e=>setF({...f,[k]:e.target.value})}/>}</label>)}<label className="wide"><span>notes</span><textarea value={f.notes} onChange={e=>setF({...f,notes:e.target.value})}/></label><button>Save Trade</button></form></Panel><Panel title="Trade Journal"><div className="table"><table><thead><tr><th>Date</th><th>Exchange</th><th>Pair</th><th>Side</th><th>Risk</th><th>P&L</th><th>R</th><th>Setup</th><th>Rule</th><th></th></tr></thead><tbody>{trades.map(x=><tr key={x.id}><td>{x.trade_date}</td><td>{x.exchange}</td><td>{x.pair}</td><td>{x.side}</td><td>{cash(x.risk_usd)}</td><td className={+x.pnl_usd>=0?"pos":"neg"}>{cash(x.pnl_usd)}</td><td>{Number(x.r_multiple).toFixed(2)}R</td><td>{x.setup||"—"}</td><td>{x.violation?"⚠":"OK"}</td><td><button className="delete" onClick={()=>del(x.id)}>Delete</button></td></tr>)}</tbody></table></div></Panel></>}
 {tab==="Risk"&&<Panel title="Risk Rules"><div className="form">{[["equity","Account Equity"],["max_risk_pct","Max Risk / Trade %"],["daily_loss_limit","Daily Max Loss"],["max_trades_day","Max Trades / Day"],["max_loss_streak","Max Loss Streak"]].map(([k,l])=><label key={k}><span>{l}</span><input type="number" value={risk[k]} onChange={e=>setRisk({...risk,[k]:e.target.value})}/></label>)}<button onClick={saveRisk}>Save Risk Settings</button></div></Panel>}</main>}
function Panel({title,children,month,setMonth}){return <section className="panel"><div className="panelHead"><h2>{title}</h2>{month&&<div><button onClick={()=>setMonth(new Date(month.getFullYear(),month.getMonth()-1,1))}>‹</button><b>{month.toLocaleString(undefined,{month:"short",year:"numeric"})}</b><button onClick={()=>setMonth(new Date(month.getFullYear(),month.getMonth()+1,1))}>›</button></div>}</div><div className="body">{children}</div></section>}